spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

logging:
  level:
    root: WARN
    com.xrpshield: INFO
    org.springframework.web: WARN

