spring:
  config:
    activate:
      on-profile: prod
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    root: WARN
    com.xrpshield: INFO
    org.springframework.web: WARN

